config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  resources :books
  get '/sign-up', to: 'registration#new'
  post '/sign-up', to: 'registration#create'

  get '/sign-in', to: 'session#new'
  post '/sign-in', to: 'session#create'

  delete '/logout', to: 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, message: 'O título é obrigatório'
  validates_presence_of :author, message: 'O autor é obrigatório'
  validates_presence_of :publication_year, message: 'O ano de publicação é obrigatório'
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :books

  validates_presence_of :name, message: 'O nome é obrigatório.'
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'O email não é válido.' }
  validates_uniqueness_of :email, message: 'Email já registrado.'
  validates_length_of :password, in: 6..30, message: 'A senha deve ter pelo menos 6 caracteres.'
  validate :check_password_confirmation
  def check_password_confirmation
    errors.add(:password_confirmation, 'As senhas devem ser iguais.') if password != password_confirmation
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in
    redirect_to sign_in_path, alert: 'Você precisa entrar conectado.' if Current.user.nil?
  end

  def require_user_not_logged_in
    redirect_to root_path if Current.user
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :require_user_logged_in, only: %i[index new edit create update destroy]

  # GET /books or /books.json
  def index
    results_per_page = 5
    param_page = params[:page].nil? || params[:page].to_i.zero? ? 1 : Integer(params[:page])
    total_pages = Book.where(user_id: Current.user.id).page(1).per(results_per_page).total_pages
    page = Book.where(user_id: Current.user.id).page(param_page).per(results_per_page).out_of_range? ? total_pages : param_page
    initial_pagination = if page < 3 || total_pages < 7
                           1
                         elsif total_pages - page < 4
                           total_pages - 5
                         else
                           page - 2
                         end

    @books = Book.where(user_id: Current.user.id).order(created_at: :desc).page(page).per(results_per_page)
    @info = { page: page, total_pages: total_pages,
              initial_pagination: initial_pagination }
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    redirect_to root_path if Current.user.id != @book.user_id
  end

  # POST /books or /books.json
  def create
    @book = Current.user.books.create(book_params)

    if @book.save
      ActionCable.server.broadcast 'room_channel', { book: @book, userName: Current.user.name }
      redirect_to books_path, notice: 'Livro cadastrado com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    return unless Current.user.id == @book.user_id

    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Livro atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    return unless Current.user.id == @book.user_id

    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Livro excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    begin
      @book = Book.find(params[:id])
    rescue
      redirect_to books_url
    end
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :publication_year, :image)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    reuslts_per_page = 5
    param_page = params[:page].nil? || params[:page].to_i.zero? ? 1 : Integer(params[:page])
    total_pages = Book.page(1).per(reuslts_per_page).total_pages
    page = Book.page(param_page).per(reuslts_per_page).out_of_range? ? total_pages : param_page
    initial_pagination = if page < 3 || total_pages < 7
                           1
                         elsif total_pages - page < 4
                           total_pages - 5
                         else
                           page - 2
                         end

    @books = Book.order(created_at: :desc).page(page).per(reuslts_per_page)
    @info = { page: page, total_pages: total_pages,
              initial_pagination: initial_pagination }
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  before_action :require_user_not_logged_in

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to books_path, notice: 'Conta criada com sucesso'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to books_path, notice: "Conectado com sucesso"
    else
      flash[:alert] = "Email ou senha incorretos"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :publication_year %>
    <%= form.number_field :publication_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1 class="text-center mt-2">Editar Livro</h1>
<div id="edit-book-page" class="d-flex flex-column align-items-center mx-auto">
  <%= form_with model: @book, class: "w-100 max-w-50 p-3 border border-secondary shadow bg-off-white-light", url: @book do |form| %>
    <% if form.object.errors.any? %>
      <div class="alert alert-danger">
        <% form.object.errors.messages.each do |attr, message| %>
          <div><%= message.first %></div>
        <% end %>
      </div>
    <% end %>

    <div class="mb-3 position-relative" id="lll">
      <%= form.label "Título" %>
      <%= form.text_field :title, class: "dropdown-toggle form-control", href: "#", id: "book_title",
                          role: "button", "data-bs-toggle": "dropdown", "aria-expanded": "false", autocomplete: "off" %>
      <ul id="result-list" class="dropdown-menu " aria-labelledby="title">
      </ul>
    </div>

    <div class="mb-3">
      <%= form.label "Autor" %>
      <%= form.text_field :author, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label "Ano de publicação" %>
      <%= form.number_field :publication_year, class: "form-control" %>
    </div>
    <div class="d-flex justify-content-evenly">
      <%= link_to 'Excluir', @book, method: :delete, class: "btn btn-danger",
                  data: { confirm: 'Você tem certeza que deseja excluir o livro?' } %>
      <%= form.submit "Salvar Livro", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<h1>Meus Livros</h1>

<%= link_to 'Adicionar Livro', new_book_path, class: 'btn btn-primary my-2' %>
<ul id="book-list" class="list-group">
  <% @books.each do |book| %>
    <li class="list-group-item d-flex align-items-center justify-content-between bg-off-white">
      <div class="d-flex gap-2">
        <% if book.image %>
          <%= image_tag book.image, alt: book.title, class: "img-thumbnail w-4_5 min-h-6" %>
        <% end %>
        <div>
          <%= link_to book, class: "text-decoration-none text-black underline-hover" do %>
            <h5><%= book.title %></h5>
          <% end %>
          <span><%= book.author %></span>,
          <span><%= book.publication_year %></span>
        </div>
      </div>
      <div class="d-flex flex-column gap-1 d-md-inline">
        <%= link_to 'Editar', edit_book_path(book), class: "btn btn-primary" %>
        <%= link_to 'Excluir', book, method: :delete, class: "btn btn-danger",
                    data: { confirm: 'Você tem certeza que deseja excluir o livro?' } %>
      </div>
    </li>
  <% end %>
</ul>


<% if @books.length > 0 %>
  <nav class="mt-4 d-flex justify-content-center">
    <ul class="pagination">
      <li class="page-item<%= (Integer(@info[:page]) == 1) ? ' disabled' : '' %>">
        <%= link_to "Anterior", books_path(page: Integer(@info[:page]) - 1), class: "page-link" %>
      </li>
      <% (@info[:initial_pagination]..[@info[:total_pages], 6].min + @info[:initial_pagination] - 1).each do |i| %>
        <li class="page-item<%= +(Integer(@info[:page]) == i ? ' active' : '') %>">
          <%= link_to i, books_path(page: i), class: "page-link" %>
        </li>
      <% end %>
      <li class="page-item<%= Integer(@info[:page]) == Integer(@info[:total_pages]) ? ' disabled' : '' %>">
        <%= link_to "Próxima", books_path(page: Integer(@info[:page]) + 1), class: "page-link" %>
      </li>
    </ul>
  </nav>
<% end %>

app/views/books/new.html.erb
<h1 class="text-center mt-2">Novo Livro</h1>
<div id="new-book-page" class="d-flex flex-column align-items-center mx-auto">
  <%= form_with model: @book, class: "w-100 max-w-50 p-3 border border-secondary shadow bg-off-white-light", url: books_path do |form| %>
    <% if form.object.errors.any? %>
      <div class="alert alert-danger">
        <% form.object.errors.messages.each do |attr, message| %>
          <div><%= message.first %></div>
        <% end %>
      </div>
    <% end %>

    <div class="mb-3 position-relative">
      <%= form.label "Título" %>
      <%= form.text_field :title, class: "dropdown-toggle form-control", href: "#", id: "book_title", role: "button", "data-bs-toggle": "dropdown", "aria-expanded": "false", autocomplete: "off" %>
      <ul id="result-list" class="dropdown-menu " aria-labelledby="title">
      </ul>
    </div>

    <div class="mb-3">
      <%= form.label "Autor" %>
      <%= form.text_field :author, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label "Ano de publicação" %>
      <%= form.number_field :publication_year, class: "form-control" %>
    </div>
    <%= form.text_field :image, type: "hidden" %>

    <div class="d-flex justify-content-center">
      <%= form.submit "Cadastrar Livro", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="d-flex justify-content-center">
  <div class="d-flex flex-column gap-4 mt-5 bg-off-white border border-2 rounded-3 max-w-50 p-4">
    <div class="d-flex">
      <% if @book.image %>
        <%= image_tag @book.image, alt: @book.title, class: "img-thumbnail me-3" %>
      <% end %>
      <div>
        <p>
          <strong>Title:</strong>
          <%= @book.title %>
        </p>

        <p>
          <strong>Author:</strong>
          <%= @book.author %>
        </p>

        <p>
          <strong>Publication year:</strong>
          <%= @book.publication_year %>
        </p>
      </div>
    </div>
    <% if Current.user && Current.user.id == @book.user_id %>
      <div class="d-flex justify-content-evenly">
        <%= link_to 'Excluir', @book, method: :delete, class: "btn btn-danger",
                    data: { confirm: 'Você tem certeza que deseja excluir o livro?' } %>
        <%= link_to 'Editar', edit_book_path(@book), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookOnRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render partial: "shared/navbar" %>
<div class="container">
  <%= render partial: "shared/flash" %>
  <%= yield %>
</div>
</body>
</html>

app/views/main/index.html.erb
<h1>Todos Livros</h1>

<div id="home-page">
  <ul id="book-list" class="list-group">
    <% @books.each do |book| %>
      <li class="list-group-item d-flex align-items-center justify-content-between bg-off-white">
        <div class="d-flex gap-2">
          <% if book.image %>
            <%= image_tag book.image, alt: book.title, class: "img-thumbnail w-4_5 min-h-6" %>
          <% end %>
          <div>
            <%= link_to book, class: "text-decoration-none text-black underline-hover" do %>
              <h5><%= book.title %></h5>
            <% end %>
            <span><%= book.author %></span>,
            <span><%= book.publication_year %></span>
            <p class="mb-0 mt-4">Lido por: <%= User.where(id: book.user_id).first.name %></p>
          </div>
        </div>
        <div class="d-flex flex-column gap-1 d-md-inline">
          <% if Current.user && Current.user.id == book.user_id %>
            <%= link_to 'Editar', edit_book_path(book), class: "btn btn-primary" %>
            <%= link_to 'Excluir', book, method: :delete, class: "btn btn-danger",
                        data: { confirm: 'Você tem certeza que deseja excluir o livro?' } %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<% if @books.length > 0 %>
  <nav class="mt-4 d-flex justify-content-center">
    <ul class="pagination">
      <li class="page-item<%= (Integer(@info[:page]) == 1) ? ' disabled' : '' %>">
        <%= link_to "Anterior", root_path(page: Integer(@info[:page]) - 1), class: "page-link" %>
      </li>
      <% (@info[:initial_pagination]..[@info[:total_pages], 6].min + @info[:initial_pagination] - 1).each do |i| %>
        <li class="page-item<%= +(Integer(@info[:page]) == i ? ' active' : '') %>">
          <%= link_to i, root_path(page: i), class: "page-link" %>
        </li>
      <% end %>
      <li class="page-item<%= Integer(@info[:page]) == Integer(@info[:total_pages]) ? ' disabled' : '' %>">
        <%= link_to "Próxima", root_path(page: Integer(@info[:page]) + 1), class: "page-link" %>
      </li>
    </ul>
  </nav>
<% end %>

app/views/session/new.html.erb
<h1 class="text-center mt-2">Entrar</h1>

<div id="new-book-page" class="d-flex flex-column align-items-center mx-auto">
  <%= form_with class: "w-100 max-w-25 p-3 border border-secondary shadow bg-off-white-light", url: sign_in_path do |form| %>
    <div class="mb-3">
      <%= form.label "Email" %>
      <%= form.text_field :email, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label "Senha" %>
      <%= form.password_field :password, class: "form-control" %>
    </div>

    <div class="d-flex justify-content-center">
      <%= form.submit "Entrar", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-lg-5">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Página Inicial", root_path, class: "nav-link" + (current_page?(root_path) ? ' active' : '') %>
        </li>
        <li class="nav-item">
          <%= link_to "Meus Livros", books_path, class: "nav-link" + (current_page?(books_path) ? ' active' : '') %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= Current.user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= button_to "Sair", logout_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item mx-2 my-1 my-lg-0">
            <%= link_to "Entrar", sign_in_path, class: "btn btn-outline-light" %>
          </li>
          <li class="nav-item mx-2 my-1 my-lg-0">
            <%= link_to "Cadastre-se", sign_up_path, class: "btn btn-outline-light" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>